### ISSUE TITLE
Pipe and Stream event data both are not working

### ISSUE THREAD

**Issue by Tabish13** [jyu213/ssh2-sftp-client#122] opened 2019-03-01 11:54 UTC
var sftp = new Client();
sftp.connect({
    host: 'host',
    port: '22',
    username: 'user',
    password: 'pass'
}).then(() => {
    return sftp.get("/home/tabish/test/CFD1.CSV", null, "utf8");
}).then(function(data) {
    console.log("Started");
    var file = fs.createWriteStream("./excel/test.csv");
    file.on('finish', function() {
        console.log("Finished");
        sftp.end();
    });
    data.pipe(file);
}).catch((err) => {
    console.log(err, 'catch error');
    sftp.end();
    cb(err, null);
});

Output: Started
I am not getting any error or finished in console and terminal get stuck 

readable.readableFlowing i,e data.readableFlowing is returns false
even tried to readable.resume() i,e data.resume() and not getting any data event or readable event.

**Comment by theophilusx** [comment] 2019-03-03 22:39
I think this is a duplicate of #106 

There appears to be an incompatibility with node 10.x and how the module is handling streams. I believe my fork at https://github.com/tehophilusx/ssh2-sftp-client fixes this issue. I will be submitting a PR once I'm satisfied the changes are all OK.  Note however, there are some breaking changes in the updated version.

**Comment by Tabish13** [comment] 2019-03-04 06:31
Yes thanks @theophilusx  it is similar to that of #106 
@j1151300783  as provided a workaround for same in #106

**Closed** 2019-03-04 06:33 UTC
